name: CI-NODE-14.15.4-CHROME-LIGHTHOUSE

on:
  push:
    branches: [master]
    paths:
      - node-14.15.4-chrome-lighthouse/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build the Docker images
        run: |
          docker build . --file node-14.15.4-chrome-lighthouse/Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/node-14.15.4-chrome-lighthouse:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/node-14.15.4-chrome-lighthouse:latest