name: CI-NODE-16.14.2-CHROME

on:
  push:
    branches: [master]
    paths:
      - node-16.14.2-chrome/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build the Docker images
        run: |
          docker build . --file node-16.14.2-chrome/Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/node-16.14.2-chrome:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/node-16.14.2-chrome:latest